/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <time.h>
#include <stdlib.h>
#include "date.h"

long *
bin_date_1_svc(void *argp, struct svc_req *rqstp)
{
	static long  result;

    result = time((long *)0);

    printf("time = %ld\n", result);

	return &result;
}

char **
str_date_1_svc(long *bintime, struct svc_req *rqstp)
{
	static char * result;

    result = ctime(bintime);

    printf("date = %s", result);

	return &result;
}

